name: CI

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Extension
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        working-directory: multi-tool-extension
        run: npm install

      - name: Run ESLint
        working-directory: multi-tool-extension
        run: npm run lint